version: '3'
services:
  app:
    build: .
    ports:
      - "8071:8071"
    depends_on:
      - dbSetup
    environment:
      - db.host=dbSetup
      - db.port=5432
      - db.user=postgres
      - db.pass=some-pass
      - db.name=postgres
  dbSetup:
    image: postgres:alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=some-pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=dbSetup 
    volumes:
     - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
